### ISSUE TITLE
No changelog for some devices

### ISSUE THREAD

**Issue by TomTasche** [tonky/gae-cm-nightlies#18]
Hey there,

Unfortunately I'm not able to check the changelog for my girlfriend's P970. It says the mirror might be down, but there are new builds popping up at get.cm every few days though.

Any idea what's wrong here?

Have a great day
Tom

**Comment by tonky** [comment]
i guess you missed the announcement, cm7 nightlies are separate now: http://cm-7-nightlies.appspot.com/?device=p970 :)

**Comment by TomTasche** [comment]
Ha! I've used the wrong URL. ;) I thought it's cm7-nightlies.appspot.com.

Thanks!
